export enum ApplicationPages {
  ExchangeRates = 12,
  TimeCategory = 49,
  Quality = 50,
  Phase = 51,
  Nature = 52,
  Medium = 53,
  MediaCategory = 54,
  ActivityType = 55,
  Assets = 56,
  Liabilities = 57,
  Income = 58,
  Expense = 59,
  BalanceSheet = 60,
  IncomeExpenseReport = 61,
  ExchangeGainLoss=29,
  Vouchers = 62,
  Clients = 63,
  UnitRates = 64,
  Jobs = 38,
  Contracts = 66,
  MyProjects = 67,
  Donors = 68,
  ProjectDetails = 69,
  Proposal = 70,
  CriteriaEvaluation = 71,
  Producer = 72,
  Policy = 73,
  ProjectJobs = 74,
  ProjectActivities = 75,
  Channel = 76,
  Scheduler = 77,
  ProjectDashboard = 78,
  ProjectCashFlow = 79,
  ProjectBudgetLine = 80,
  BroadCastPolicy = 81,
  ProposalReport = 82,
  Users = 1,
  ChartOfAccount = 2,
  JournalCodes = 3,
  CurrencyCodes = 4,
  OfficeCodes = 5,
  FinancialYear = 6,
  PensionRate = 7,
  EmployeeContract = 8,
  AppraisalQuestions = 9,
  TechnicalQuestions = 10,
  EmailSettings = 11,
  LeaveReason = 13,
  Profession = 14,
  Department = 15,
  Qualification = 16,
  Designation = 17,
  JobGrade = 18,
  SalaryHead = 19,
  SalaryTaxReportContent = 20,
  SetPayrollAccount = 21,
  Journal = 23,
  LedgerStatement = 24,
  BudgetBalance = 25,
  TrialBalance = 26,
  FinancialReport = 27,
  CategoryPopulator = 28,
  GainLossTransaction = 30,
  PensionPayments = 31,
  Employees = 32,
  PayrollDailyHours = 33,
  Holidays = 34,
  Attendance = 35,
  ApproveLeave = 36,
  MonthlyPayrollRegister = 37,
  Interview = 39,
  EmployeeAppraisal = 40,
  Advances = 41,
  Summary = 42,
  Categories = 43,
  StoreSourceCodes = 44,
  PaymentTypes = 45,
  Store = 46,
  ProcurementSummary = 47,
  DepreciationReport = 48,
  MarketingJobs = 65,
  ProjectIndicators= 83,
  ProjectPeople= 84,
  VoucherSummaryreport= 85,
  HiringRequests= 86
}

export enum ApplicationModule {
  Marketing = 6,
  AccountingNew = 7,
  Projects = 8
}

export const projectPagesMaster = {
  ProjectJobs: ApplicationPages.ProjectJobs,
  ProjectActivities: ApplicationPages.ProjectActivities,
  MyProjects: ApplicationPages.MyProjects,
  Donors: ApplicationPages.Donors,
  ProjectDetails: ApplicationPages.ProjectDetails,
  Proposal: ApplicationPages.Proposal,
  CriteriaEvaluation: ApplicationPages.CriteriaEvaluation,
  ProjectDashboard: ApplicationPages.ProjectDashboard,
  ProjectCashFlow: ApplicationPages.ProjectCashFlow,
  ProjectBudgetLine: ApplicationPages.ProjectBudgetLine,
  ProposalReport: ApplicationPages.ProposalReport,
  ProjectIndicators: ApplicationPages.ProjectIndicators,
  ProjectPeople: ApplicationPages.ProjectPeople,
  HiringRequests: ApplicationPages.HiringRequests
};

export const marketingPagesMaster = {
  TimeCategory: ApplicationPages.TimeCategory,
  Quality: ApplicationPages.Quality,
  Phase: ApplicationPages.Phase,
  Nature: ApplicationPages.Nature,
  Medium: ApplicationPages.Medium,
  MediaCategory: ApplicationPages.MediaCategory,
  ActivityType: ApplicationPages.ActivityType,
  Clients: ApplicationPages.Clients,
  UnitRates: ApplicationPages.UnitRates,
  Jobs: ApplicationPages.Jobs,
  Contracts: ApplicationPages.Contracts,
  Scheduler: ApplicationPages.Scheduler,
  Producer: ApplicationPages.Producer,
  Channels: ApplicationPages.Channel,
  BroadCastPolicy: ApplicationPages.BroadCastPolicy
};

export const accountingNewMaster = {
  Assets: ApplicationPages.Assets,
  Liabilities: ApplicationPages.Liabilities,
  Income: ApplicationPages.Income,
  Expense: ApplicationPages.Expense,
  BalanceSheet: ApplicationPages.BalanceSheet,
  IncomeExpenseReport: ApplicationPages.IncomeExpenseReport,
  Vouchers: ApplicationPages.Vouchers,
  ExchangeRates: ApplicationPages.ExchangeRates,
  ExchangeGainLoss: ApplicationPages.ExchangeGainLoss,
  VoucherSummaryReport: ApplicationPages.VoucherSummaryreport
};

export const configurationPagesMaster = {
  JournalCodes: ApplicationPages.JournalCodes,
  CurrencyCodes: ApplicationPages.CurrencyCodes,
  OfficeCodes: ApplicationPages.OfficeCodes,
  FinancialYear: ApplicationPages.FinancialYear,
  PensionRate: ApplicationPages.PensionRate,
  Proposal: ApplicationPages.Proposal,
  EmployeeContract: ApplicationPages.EmployeeContract,
  AppraisalQuestions: ApplicationPages.EmployeeContract,
  TechnicalQuestions: ApplicationPages.TechnicalQuestions,
  EmailSettings: ApplicationPages.EmailSettings,
  ProposalReport: ApplicationPages.ProposalReport,
  LeaveType: ApplicationPages.LeaveReason,
  Profession: ApplicationPages.Profession,
  Department: ApplicationPages.Department,
  Qualification: ApplicationPages.Qualification,
  Designation: ApplicationPages.Designation,
  JobGrade: ApplicationPages.JobGrade,
  SalaryHead: ApplicationPages.SalaryHead,
  SalaryTaxReportContent: ApplicationPages.SalaryTaxReportContent,
  SetPayrollAccount: ApplicationPages.SetPayrollAccount
};

export const HRPagesMaster = {
  Employees: ApplicationPages.Employees,
  PayrollDailyHours: ApplicationPages.PayrollDailyHours,
  Holidays: ApplicationPages.Holidays,
  Attendance: ApplicationPages.Attendance,
  ApproveLeave: ApplicationPages.ApproveLeave,
  MonthlyPayrollRegister: ApplicationPages.MonthlyPayrollRegister,
  Jobs: ApplicationPages.Jobs,
  Interview: ApplicationPages.Interview,
  EmployeeAppraisal: ApplicationPages.EmployeeAppraisal,
  Advances: ApplicationPages.Advances,
  Summary: ApplicationPages.Advances
};

export const StorePagesMaster = {
  Categories: ApplicationPages.Categories,
  StoreSourceCodes: ApplicationPages.StoreSourceCodes,
  PaymentTypes: ApplicationPages.PaymentTypes,
  Store: ApplicationPages.Store,
  ProcurementSummary: ApplicationPages.ProcurementSummary,
  DepreciationReport: ApplicationPages.DepreciationReport
};
