apiVersion: v1
kind: Deployment
metadata:
  name: {{ .Values.web.name }}
  labels:
    app: {{ .Values.web.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{.Values.web.name}}
  template:
    metadata:
      labels:
        app: {{.Values.web.name}}
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: {{ .Values.web.name }}
          image: {{ .Values.web.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secrets/gcp/credentials.json
          - name: POSTGRES_DB_HOST
            value: 127.0.0.1:5432
          - name: DEFAULT_CORS_POLICY_NAME
            value: {{ .Values.cors.name}}
          - name: DEFAULT_CORS_POLICY_URL
            value: {{ .Values.cors.url }}
          volumeMounts:
            - name: APPLICATION_GCP_SERVICEACCOUNT
              mountPath: /secrets
              readOnly: true
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          imagePullPolicy: IfNotPresent
          command: ["/cloud_sql_proxy",
                    "-instances=clear-fusion-193608:europe-west4:cf-prod-primary=tcp:3306",
                    "-credential_file=/secrets/gcp/credentials.json"]
          volumeMounts:
            - name: APPLICATION_GCP_SERVICEACCOUNT
              mountPath: /secrets
              readOnly: true
      volumes:
      - name: APPLICATION_GCP_SERVICEACCOUNT
        secret:
          secretName: APPLICATION_GCP_SERVICEACCOUNT
          items:
          - key: APPLICATION_GCP_SERVICEACCOUNT
            path: gcp/credentials.json

