apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.gitlab.com/app: {{.Values.ci.project.path}}
    app.gitlab.com/env: {{.Values.ci.project.environment}}
  name: {{ .Release.Name }}
  namespace: {{.Values.deployment.namespace}}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        app.gitlab.com/app: {{.Values.ci.project.path}}
        app.gitlab.com/env: {{.Values.ci.project.environment}}
      labels:
        app: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.web.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secrets/gcp/credentials.json
          - name: LINUX_DBCONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secrets
                key: appdbconnectionstring
          - name: POSTGRES_DB_HOST
            value: 127.0.0.1:5432
          - name: POSTGRES_DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secrets
                key: postgresuser
          - name: POSTGRES_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secrets
                key: postgrespassword
          - name: DEFAULT_CORS_POLICY_NAME
            value: localhost
          - name: DEFAULT_CORS_POLICY_URL
            value: https://legacyapptestedg.cha-net.org
          - name: WEB_SITE_URL
            value: http://localhost:4000/
          - name: GOOGLE_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secrets
                key: googlebucketname
          - name: DOCS_URL
            value: {{ .Values.app.docsurl }}
          - name: ASPNETCORE_ENVIRONMENT
            value: {{ .Values.app.env }}
          - name: AUTH_TENANT_DOMAIN
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secrets
                key: authtenantdomain
          - name: AUTH_WEBAPP_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secrets
                key: authwebappclientid
          - name: AUTH_WEBAPP_CALLBACK_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secrets
                key: authwebappcallbackurl
          - name: AUTH_WEBAPP_API_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secrets
                key: authwebappapiurl
          - name: AUTH_WEBAPI_API_IDENTIFIER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secrets
                key: authwebapiapiidentifier
          volumeMounts:
            - name: application-gcp-serviceaccount
              mountPath: /secrets
              readOnly: true
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          imagePullPolicy: IfNotPresent
          command: ["/cloud_sql_proxy",
                    "-instances=clear-fusion-193608:europe-west4:cf-prod-primary=tcp:5432",
                    "-credential_file=/secrets/gcp/credentials.json"]
          volumeMounts:
            - name: application-gcp-serviceaccount
              mountPath: /secrets
              readOnly: true
      volumes:
      - name: application-gcp-serviceaccount
        secret:
          secretName: {{ .Release.Name }}-secrets
          items:
          - key: appserviceaccount
            path: gcp/credentials.json