apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    app.gitlab.com/app: {{.Values.ci.project.path}}
    app.gitlab.com/env: {{.Values.ci.project.environment}}
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: {{ .Values.web.name }}-ingress
  namespace: {{.Values.deployment.namespace}}
spec:
  tls:
  - hosts:
    - {{.Values.web.host}}
    secretName: {{.Values.web.name}}-host-tls-secret
  rules:
  - host: {{ .Values.web.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.web.name }}-service
          servicePort: 80