apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    app.gitlab.com/app: {{.Values.ci.project.path}}
    app.gitlab.com/env: {{.Values.ci.project.environment}}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  name: {{ .Release.Name }}-ingress
  namespace: {{.Values.deployment.namespace}}
spec:
  tls:
  - hosts:
    - {{.Values.web.host}}
    secretName: {{ .Release.Name }}-host-tls-secret
  rules:
  - host: {{ .Values.web.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-service
          servicePort: clientapp-port