apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.web.name }}{{ .Release.Revision }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx-ingress
spec:
  rules:
  - host: {{ .Values.web.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.web.name}}
          servicePort: 80