apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    app.gitlab.com/app: {{.Values.ci.project.path}}
    app.gitlab.com/env: {{.Values.ci.project.environment}}
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: {{ .Release.Name }}{{ .Release.Revision }}-ingress
  namespace: {{.Values.deployment.namespace}}
spec:
  tls:
  - hosts:
    - {{.Values.web.host}}
    secretName: {{ .Release.Name }}{{ .Release.Revision }}-host-tls-secret
  rules:
  - host: {{ .Values.web.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}{{ .Release.Revision }}-service
          servicePort: {{ .Release.Name }}{{ .Release.Revision }}-service-http-port