apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.web.name }}-secrets
type: Opaque
data:
  appdbconnectionstring: {{ .Values.secret.appdbconnectionstring }}
  postgresuser: {{ .Values.secret.postgresuser }}
  postgrespassword: {{ .Values.secret.postgrespassword }}
  appserviceaccount: {{ .Values.secret.appserviceaccount }}
  googlebucketname: {{ .Values.secret.googlebucketname }}