apiVersion: v1
kind: Secret
metadata:
  annotations:
    app.gitlab.com/app: {{.Values.ci.project.path}}
    app.gitlab.com/env: {{.Values.ci.project.environment}}
  name: {{ .Values.web.name }}-secrets
  namespace: {{.Values.deployment.namespace}}
type: Opaque
data:
  appdbconnectionstring: {{ .Values.secret.appdbconnectionstring }}
  postgresuser: {{ .Values.secret.postgresuser }}
  postgrespassword: {{ .Values.secret.postgrespassword }}
  appserviceaccount: {{ .Values.secret.appserviceaccount }}
  googlebucketname: {{ .Values.secret.googlebucketname }}