apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.web.name }}-secrets
type: Opaque
data:
  app-db-connectionstring: {{ .Values.secret.app-db-connectionstring }}
  postgres-user: {{ .Values.secret.postgres-user }}
  postgres-password: {{ .Values.postgres-password }}
  app-service-account: {{ .Values.secret.app-service-account }}
  google-bucket-name: {{ .Values.secret.google-bucket-name }}