apiVersion: v1
kind: Secret
metadata:
  annotations:
    app.gitlab.com/app: {{.Values.ci.project.path}}
    app.gitlab.com/env: {{.Values.ci.project.environment}}
  name: {{ .Release.Name }}{{ .Release.Revision }}-secrets
  namespace: {{.Values.deployment.namespace}}
type: Opaque
data:
  appdbconnectionstring: {{ .Values.app.secret.appdbconnectionstring }}
  postgresuser: {{ .Values.app.secret.postgresuser }}
  postgrespassword: {{ .Values.app.secret.postgrespassword }}
  appserviceaccount: {{ .Values.app.secret.appserviceaccount }}
  googlebucketname: {{ .Values.app.secret.googlebucketname }}