apiVersion: v1
kind: Secret
metadata:
  annotations:
    app.gitlab.com/app: {{.Values.ci.project.path}}
    app.gitlab.com/env: {{.Values.ci.project.environment}}
  name: {{ .Release.Name }}-secrets
  namespace: {{.Values.deployment.namespace}}
type: Opaque
data:
  appdbconnectionstring: {{ .Values.app.secret.appdbconnectionstring }}
  postgresuser: {{ .Values.app.secret.postgresuser }}
  postgrespassword: {{ .Values.app.secret.postgrespassword }}
  appserviceaccount: {{ .Values.app.secret.appserviceaccount }}
  googlebucketname: {{ .Values.app.secret.googlebucketname }}
  authtenantdomain: {{ .Values.app.secret.authtenantdomain }}
  authwebappclientid: {{ .Values.app.secret.authwebappclientid }}
  authwebappcallbackurl: {{ .Values.app.secret.authwebappcallbackurl }}
  authwebappapiurl: {{ .Values.app.secret.authwebappapiurl }}
  authwebapiapiidentifier: {{ .Values.app.secret.authwebapiapiidentifier }}