apiVersion: v1
kind: Service
metadata:
    annotations:
        app.gitlab.com/app: {{.Values.ci.project.path}}
        app.gitlab.com/env: {{.Values.ci.project.environment}}
    name: {{ .Values.web.name }}-service
    namespace: {{.Values.deployment.namespace}}
    labels:
        app: {{ .Values.web.name }}
    
spec:
    ports:
        - name: http
          port: 80
          targetPort: 80
    selector:
        app: {{ .Values.web.name }}