apiVersion: v1
kind: Service
metadata:
    annotations:
        app.gitlab.com/app: {{.Values.ci.project.path}}
        app.gitlab.com/env: {{.Values.ci.project.environment}}
    name: {{ .Release.Name }}{{ .Release.Revision }}-service
    namespace: {{.Values.deployment.namespace}}
    labels:
        app: {{ .Release.Name }}
spec:
    ports:
        - name: clientapp-port
          port: 80
          protocol: TCP
          targetPort: 80
    selector:
        app: {{ .Release.Name }}
    type: NodePort