version: 2.1
jobs:
  build-job:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: dotnet restore HumanitarianAssistance/HumanitarianAssistance.WebAPI.csproj
      - run: dotnet publish HumanitarianAssistance/HumanitarianAssistance.WebAPI.csproj -c Release -o release
      