version: 2.1
jobs:
  build:
    docker:
      # - image: mcr.microsoft.com/dotnet/core/sdk:2.1
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - run: 
          name: install node
          command: "curl -sL https://deb.nodesource.com/setup_10.x | bash -  && apt update  && apt install -y nodejs"
      - run: npm cache clean -f
      - run: npm install -g n
      - run: n stable
      - run: node -v
      - run: npm -v
      - run: npm install -g @angular/cli
      
      - checkout

      - run: dotnet restore
      - run: dotnet publish HumanitarianAssistance.WebApi/HumanitarianAssistance.WebApi.csproj -c Release -o release
  
