version: 2.1
jobs:
  build-job:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run: dotnet restore HumanitarianAssistance/HumanitarianAssistance.WebAPI.csproj
      - run: dotnet publish HumanitarianAssistance/HumanitarianAssistance.WebAPI.csproj -c Release -o release
      - run: mkdir HumanitarianAssistance/release/Documents
      - persist_to_workspace:
          root: .
          paths: 
            - HumanitarianAssistance/release
            - Dockerfile
            - .dockerignore
  push-container:
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: workspace
      - run: find .
      - run:
          name: Set up Google cloud SDK. Important to set up cluster based on deployment
          command: |
            echo $GCLOUD_SERVICE_KEY > gcloud-service-key.json
            gcloud auth activate-service-account --key-file gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - setup_remote_docker
      - run:
          name: Tag docker image to GCR registry
          command: |
            docker build -t ${APPLICATION_NAME}:${CIRCLE_SHA1} ./workspace
            docker tag ${APPLICATION_NAME}:${CIRCLE_SHA1} eu.gcr.io/${GOOGLE_PROJECT_ID}/${APPLICATION_NAME}:${CIRCLE_SHA1}
            gcloud auth configure-docker
            docker push eu.gcr.io/${GOOGLE_PROJECT_ID}/${APPLICATION_NAME}:${CIRCLE_SHA1}
      - run: echo ${APPLICATION_NAME}:${CIRCLE_SHA1}
  deploy-staging-edg:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: Set up Google cloud SDK. Important to set up cluster based on deployment
          command: |
            echo $GCLOUD_SERVICE_KEY > gcloud-service-key.json
            gcloud auth activate-service-account --key-file gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_STAGING_CLUSTER_NAME}
      - setup_remote_docker
      - run:
          name: Patch K8 deployment with new container
          command: |
            kubectl patch deployment ${KUBDEPLOYMENT_EDGSTAGINGAPI_STAGING} -p '{"spec":{"template":{"spec":{"containers":[{"name":"'"$APPLICATION_NAME"'","image":"eu.gcr.io/'"$GOOGLE_PROJECT_ID"'/'"$APPLICATION_NAME"':'"$CIRCLE_SHA1"'"}]}}}}'
            kubectl rollout status deployment/${KUBDEPLOYMENT_EDGSTAGINGAPI_STAGING}
            kubectl get pods
  deploy-staging:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: Set up Google cloud SDK. Important to set up cluster based on deployment
          command: |
            echo $GCLOUD_SERVICE_KEY > gcloud-service-key.json
            gcloud auth activate-service-account --key-file gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_STAGING_CLUSTER_NAME}
      - setup_remote_docker
      - run:
          name: Patch K8 deployment with new container
          command: |
            kubectl patch deployment ${KUBDEPLOYMENT_API_STAGING} -p '{"spec":{"template":{"spec":{"containers":[{"name":"'"$APPLICATION_NAME"'","image":"eu.gcr.io/'"$GOOGLE_PROJECT_ID"'/'"$APPLICATION_NAME"':'"$CIRCLE_SHA1"'"}]}}}}'
            kubectl rollout status deployment/${KUBDEPLOYMENT_API_STAGING}
            kubectl get pods
  deploy-bmount-prod:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: Set up Google cloud SDK. Important to set up cluster based on deployment
          command: |
            echo $GCLOUD_SERVICE_KEY > gcloud-service-key.json
            gcloud auth activate-service-account --key-file gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_PRODUCTION_CLUSTER_NAME}
      - setup_remote_docker
      - run:
          name: Patch K8 deployment with new container
          command: |
            kubectl patch deployment ${KUBDEPLOYMENT_BMOUNTAPI_PROD} -p '{"spec":{"template":{"spec":{"containers":[{"name":"'"$APPLICATION_NAME"'","image":"eu.gcr.io/'"$GOOGLE_PROJECT_ID"'/'"$APPLICATION_NAME"':'"$CIRCLE_SHA1"'"}]}}}}'
            kubectl rollout status deployment/${KUBDEPLOYMENT_BMOUNTAPI_PROD}
            kubectl get pods
workflows:
  version: 2.1
  clearfusion-api-build-deploy:
    jobs:
      - build-job
      - push-container:
          requires:
          - build-job
      - deploy-staging-edg:
          requires:
          - push-container
      - deploy-staging:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy-bmount-prod:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/