using System;
using System.Collections.Generic;
using System.Text;

namespace HumanitarianAssistance.Application.Project.Models
{
   public class CriteriaEveluationModel
    {
        public long ProjectId { get; set; }
        public long? DonorCEId { get; set; }
        public int? MethodOfFunding { get; set; }
        public bool? PastFundingExperience { get; set; }
        public bool? ProposalAccepted { get; set; }
        public bool? ProposalExperience { get; set; }
        public bool? Professional { get; set; }
        public bool? FundsOnTime { get; set; }
        public bool? EffectiveCommunication { get; set; }
        public bool? Dispute { get; set; }
        public bool? OtherDeliverable { get; set; }
        public string OtherDeliverableType { get; set; }
        public bool? PastWorkingExperience { get; set; }
        public bool? CriticismPerformance { get; set; }
        public bool? TimeManagement { get; set; }
        public bool? MoneyAllocation { get; set; }
        public bool? Accountability { get; set; }
        public bool? DeliverableQuality { get; set; }
        public int? DonorFinancingHistory { get; set; }
        public int? ReligiousStanding { get; set; }
        public int? PoliticalStanding { get; set; }
        public long FeasibilityId { get; set; }
        public bool? CapacityAvailableForProject { get; set; }
        public bool? TrainedStaff { get; set; }
        public bool? ByEquipment { get; set; }
        public bool? ExpandScope { get; set; }
        public bool? GeoGraphicalPresence { get; set; }
        public bool? ThirdPartyContract { get; set; }
        public int? CostOfCompensationMonth { get; set; }
        public double? CostOfCompensationMoney { get; set; }
        public bool? AnyInKindComponent { get; set; }
        public bool? UseableByOrganisation { get; set; }
        public bool? FeasibleExpertDeploy { get; set; }
        public bool? EnoughTimeForProject { get; set; }
        public bool? ProjectAllowedBylaw { get; set; }
        public bool? ProjectByLeadership { get; set; }
        public bool? IsProjectPractical { get; set; }
        public bool? PresenceCoverageInProject { get; set; }
        public bool? ProjectInLineWithOrgFocus { get; set; }
        public bool? EnoughTimeToPrepareProposal { get; set; }
        public double? ProjectRealCost { get; set; }
        public bool? IsCostGreaterthenBudget { get; set; }
        public int? PerCostGreaterthenBudget { get; set; }
        public bool? IsFinancialContribution { get; set; }
        public bool? IsSecurity { get; set; }
        public bool? IsGeographical { get; set; }
        public bool? IsSeasonal { get; set; }
        public long ProductServiceId { get; set; }
        public long EligibilityId { get; set; }
        public bool? Awareness { get; set; }
        public bool? Infrastructure { get; set; }
        public bool? CapacityBuilding { get; set; }
        public bool? IncomeGeneration { get; set; }
        public bool? Mobilization { get; set; }
        public bool? PeaceBuilding { get; set; }
        public bool? SocialProtection { get; set; }
        public bool? SustainableLivelihood { get; set; }
        public bool? Advocacy { get; set; }
        public bool? Literacy { get; set; }
        public bool? EducationCapacityBuilding { get; set; }
        public bool? SchoolUpgrading { get; set; }
        public bool? EducationInEmergency { get; set; }
        public bool? OnlineEducation { get; set; }
        public bool? CommunityBasedEducation { get; set; }
        public bool? AcceleratedLearningProgram { get; set; }
        public bool? PrimaryHealthServices { get; set; }
        public bool? ReproductiveHealth { get; set; }
        public bool? Immunization { get; set; }
        public bool? InfantandYoungChildFeeding { get; set; }
        public bool? Nutrition { get; set; }
        public bool? CommunicableDisease { get; set; }
        public bool? Hygiene { get; set; }
        public bool? EnvironmentalHealth { get; set; }
        public bool? MentalHealthandDisabilityService { get; set; }
        public bool? HealthCapacityBuilding { get; set; }
        public bool? Telemedicine { get; set; }
        public bool? MitigationProjects { get; set; }
        public bool? WaterSupply { get; set; }
        public bool? Sanitation { get; set; }
        public bool? DisasterRiskHygiene { get; set; }
        public bool? DisasterCapacityBuilding { get; set; }
        public bool? EmergencyResponse { get; set; }
        public bool? RenewableEnergy { get; set; }
        public bool? Shelter { get; set; }
        public bool? NaturalResourceManagement { get; set; }
        public bool? AggriculutreCapacityBuilding { get; set; }
        public bool? LivestockManagement { get; set; }
        public bool? FoodSecurity { get; set; }
        public bool? ResearchandPublication { get; set; }
        public bool? Horticulture { get; set; }
        public bool? Irrigation { get; set; }
        public bool? Livelihood { get; set; }
        public bool? ValueChain { get; set; }
        public bool? Children { get; set; }
        public bool? Disabled { get; set; }
        public bool? IDPs { get; set; }
        public bool? Returnees { get; set; }
        public bool? Kuchis { get; set; }
        public bool? Widows { get; set; }
        public bool? Men { get; set; }
        public bool? Women { get; set; }
        public bool? Youth { get; set; }
        public bool? DonorCriteriaMet { get; set; }
        public bool? EligibilityDealine { get; set; }
        public bool? CoPartnership { get; set; }
        public bool? IncreaseEligibility { get; set; }
        public bool? IncreaseReputation { get; set; }
        public bool? ImproveDonorRelationship { get; set; }
        public bool? GoodCause { get; set; }
        public bool? ImprovePerformancecapacity { get; set; }
        public bool? SkillImprove { get; set; }
        public bool? FillingFundingGap { get; set; }
        public bool? NewSoftware { get; set; }
        public bool? NewEquipment { get; set; }
        public bool? CoverageAreaExpansion { get; set; }
        public bool? NewTraining { get; set; }
        public bool? ExpansionGoal { get; set; }
        public double? Total { get; set; }

        public double? ProjectActivities { get; set; }
        public double? Operational { get; set; }
        public double? Overhead_Admin { get; set; }
        public double? Lump_Sum { get; set; }
        public bool? Security { get; set; }
        public bool? Staff { get; set; }
        public bool? ProjectAssets { get; set; }
        public bool? Suppliers { get; set; }
        public bool? Beneficiaries { get; set; }
        public bool? OverallOrganization { get; set; }
        public bool? DeliveryFaiLure { get; set; }
        public bool? PrematureSeizure { get; set; }
        public bool? GovernmentConfiscation { get; set; }
        public bool? DesctructionByTerroristActivity { get; set; }
        public bool? Reputation { get; set; }
        public bool? Religious { get; set; }
        public bool? Sectarian { get; set; }
        public bool? Ethinc { get; set; }
        public bool? Social { get; set; }
        public bool? Traditional { get; set; }
        public bool? FocusDivertingrisk { get; set; }
        public bool? Financiallosses { get; set; }
        public bool? Opportunityloss { get; set; }
        public List<long?> ProjectSelectionId { get; set; }

        public bool? Probablydelaysinfunding { get; set; }
        public bool? OtherOrganizationalHarms { get; set; }
        public string OrganizationalDescription { get; set; }
        public bool? IsCriteriaEvaluationSubmit { get; set; }
        public int? CurrencyId { get; set; }
        public bool? Geographical { get; set; }
        public bool? Insecurity { get; set; }
        public bool? Season { get; set; }
        public bool? Ethnicity { get; set; }
        public bool? Culture { get; set; }
        public bool? ReligiousBeliefs { get; set; }
        public string CurrencyName { get; set; }
    }
}
