using System.Collections.Generic;

namespace HumanitarianAssistance.Application.Project.Models
{
    public class CriteriaEvaluationPdfModel
    {
        public long ProjectId { get; set; }
        public long? DonorCEId { get; set; }
        public int? MethodOfFunding { get; set; }
        public string PastFundingExperience { get; set; }
        public string ProposalAccepted { get; set; }
        public string ProposalExperience { get; set; }
        public string Professional { get; set; }
        public string FundsOnTime { get; set; }
        public string EffectiveCommunication { get; set; }
        public string Dispute { get; set; }
        public string OtherDeliverable { get; set; }
        public string OtherDeliverableType { get; set; }
        public string PastWorkingExperience { get; set; }
        public string CriticismPerformance { get; set; }
        public string TimeManagement { get; set; }
        public string MoneyAllocation { get; set; }
        public string Accountability { get; set; }
        public string DeliverableQuality { get; set; }
        public int? DonorFinancingHistory { get; set; }
        public int? ReligiousStanding { get; set; }
        public int? PoliticalStanding { get; set; }
        public long FeasibilityId { get; set; }
        public string CapacityAvailableForProject { get; set; }
        public string TrainedStaff { get; set; }
        public string ByEquipment { get; set; }
        public string ExpandScope { get; set; }
        public string GeoGraphicalPresence { get; set; }
        public string ThirdPartyContract { get; set; }
        public int? CostOfCompensationMonth { get; set; }
        public double? CostOfCompensationMoney { get; set; }
        public string AnyInKindComponent { get; set; }
        public string UseableByOrganisation { get; set; }
        public string FeasibleExpertDeploy { get; set; }
        public string EnoughTimeForProject { get; set; }
        public string ProjectAllowedBylaw { get; set; }
        public string ProjectByLeadership { get; set; }
        public string IsProjectPractical { get; set; }
        public string PresenceCoverageInProject { get; set; }
        public string ProjectInLineWithOrgFocus { get; set; }
        public string EnoughTimeToPrepareProposal { get; set; }
        public double? ProjectRealCost { get; set; }
        public string IsCostGreaterthenBudget { get; set; }
        public int? PerCostGreaterthenBudget { get; set; }
        public string IsFinancialContribution { get; set; }
        public string IsSecurity { get; set; }
        public string IsGeographical { get; set; }
        public string IsSeasonal { get; set; }
        public long ProductServiceId { get; set; }
        public long EligibilityId { get; set; }
        public bool? Awareness { get; set; }
        public bool? Infrastructure { get; set; }
        public bool? CapacityBuilding { get; set; }
        public bool? IncomeGeneration { get; set; }
        public bool? Mobilization { get; set; }
        public bool? PeaceBuilding { get; set; }
        public bool? SocialProtection { get; set; }
        public bool? SustainableLivelihood { get; set; }
        public bool? Advocacy { get; set; }
        public bool? Literacy { get; set; }
        public bool? EducationCapacityBuilding { get; set; }
        public bool? SchoolUpgrading { get; set; }
        public bool? EducationInEmergency { get; set; }
        public bool? OnlineEducation { get; set; }
        public bool? CommunityBasedEducation { get; set; }
        public bool? AcceleratedLearningProgram { get; set; }
        public bool? PrimaryHealthServices { get; set; }
        public bool? ReproductiveHealth { get; set; }
        public bool? Immunization { get; set; }
        public bool? InfantandYoungChildFeeding { get; set; }
        public bool? Nutrition { get; set; }
        public bool? CommunicableDisease { get; set; }
        public bool? Hygiene { get; set; }
        public bool? EnvironmentalHealth { get; set; }
        public bool? MentalHealthandDisabilityService { get; set; }
        public bool? HealthCapacityBuilding { get; set; }
        public bool? Telemedicine { get; set; }
        public bool? MitigationProjects { get; set; }
        public bool? WaterSupply { get; set; }
        public bool? Sanitation { get; set; }
        public bool? DisasterRiskHygiene { get; set; }
        public bool? DisasterCapacityBuilding { get; set; }
        public bool? EmergencyResponse { get; set; }
        public bool? RenewableEnergy { get; set; }
        public bool? Shelter { get; set; }
        public bool? NaturalResourceManagement { get; set; }
        public bool? AggriculutreCapacityBuilding { get; set; }
        public bool? LivestockManagement { get; set; }
        public bool? FoodSecurity { get; set; }
        public bool? ResearchandPublication { get; set; }
        public bool? Horticulture { get; set; }
        public bool? Irrigation { get; set; }
        public bool? Livelihood { get; set; }
        public bool? ValueChain { get; set; }
        public bool? Children { get; set; }
        public bool? Disabled { get; set; }
        public bool? IDPs { get; set; }
        public bool? Returnees { get; set; }
        public bool? Kuchis { get; set; }
        public bool? Widows { get; set; }
        public bool? Men { get; set; }
        public bool? Women { get; set; }
        public bool? Youth { get; set; }
        public string DonorCriteriaMet { get; set; }
        public string EligibilityDealine { get; set; }
        public string CoPartnership { get; set; }
        public bool? IncreaseEligibility { get; set; }
        public bool? IncreaseReputation { get; set; }
        public bool? ImproveDonorRelationship { get; set; }
        public bool? GoodCause { get; set; }
        public bool? Others { get; set; }
        public bool? ImprovePerformancecapacity { get; set; }
        public bool? SkillImprove { get; set; }
        public bool? FillingFundingGap { get; set; }
        public bool? NewSoftware { get; set; }
        public bool? NewEquipment { get; set; }
        public bool? CoverageAreaExpansion { get; set; }
        public bool? NewTraining { get; set; }
        public string ExpansionGoal { get; set; }
        public double? Total { get; set; }

        public double? ProjectActivities { get; set; }
        public double? Operational { get; set; }
        public double? Overhead_Admin { get; set; }
        public double? Lump_Sum { get; set; }
        public string Security { get; set; }
        public string Staff { get; set; }
        public string ProjectAssets { get; set; }
        public string Suppliers { get; set; }
        public string Beneficiaries { get; set; }
        public string OverallOrganization { get; set; }
        public string DeliveryFaiLure { get; set; }
        public string PrematureSeizure { get; set; }
        public string GovernmentConfiscation { get; set; }
        public string DesctructionByTerroristActivity { get; set; }
        public string Reputation { get; set; }
        public string Religious { get; set; }
        public string Sectarian { get; set; }
        public string Ethinc { get; set; }
        public string Social { get; set; }
        public string Traditional { get; set; }
        public string FocusDivertingrisk { get; set; }
        public string Financiallosses { get; set; }
        public string Opportunityloss { get; set; }
        public List<long?> ProjectSelectionId { get; set; }

        public string Probablydelaysinfunding { get; set; }
        public string OtherOrganizationalHarms { get; set; }
        public string OrganizationalDescription { get; set; }
        public bool? IsCriteriaEvaluationSubmit { get; set; }
        public int? CurrencyId { get; set; }
        public string Geographical { get; set; }
        public string Insecurity { get; set; }
        public string Season { get; set; }
        public string Ethnicity { get; set; }
        public string Culture { get; set; }
        public string ReligiousBeliefs { get; set; }
        public string CurrencyName { get; set; }
        public string CheckedIconPath { get; set; }
        public string UnCheckedIconPath { get; set; }
        public List<CEFeasibilityExpertOtherDetailModel> CEFeasibilityExpertOtherDetailModel { get; set; }
        public List<PriorityOtherDetailModel> PriorityOtherDetailModel { get; set; }
        public List<AssumptionDetailModel> AssumptionDetailModel { get; set; }
        public List<DonorEligibilityDetailModel> DonorEligibilityDetailModel { get; set; }
        public List<SelectedProjectsModel> SelectedProjectsModel { get; set; }
        public double? TotalScore { get; set; }
        public string LogoPath { get; set; }
    }
    public class SelectedProjectsModel
    {
       public string ProjectName { get; set; } 
    }

}