apiVersion: v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: clearfusion
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: clearfusion
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: clearfusion
    spec:
      containers:
        - name: clearfusion
          image: eu.gcr.io/{{ .Values.project.name }}/clearfusion:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
